"""initial schema

Revision ID: 144d37fbad11
Revises: 
Create Date: 2026-10-02 14:35:26.894934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '144d37fbad11'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_installations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_login', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('delivery_id', sa.String(length=255), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_id')
    )
    op.create_table('repositories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('installation_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['installation_id'], ['github_installations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_full_name'), 'repositories', ['full_name'], unique=False)
    op.create_index(op.f('ix_repositories_installation_id'), 'repositories', ['installation_id'], unique=False)
    op.create_table('pull_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('explanation_comment_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'number', name='uq_pr_repo_number')
    )
    op.create_table('revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pull_request_id', sa.Uuid(), nullable=False),
    sa.Column('head_sha', sa.String(length=64), nullable=False),
    sa.Column('base_sha', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pull_request_id', 'head_sha', name='uq_revision_sha')
    )
    op.create_table('analysis_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('revision_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_status', sa.String(length=32), nullable=False),
    sa.Column('explanation_status', sa.String(length=32), nullable=False),
    sa.Column('comment_status', sa.String(length=32), nullable=False),
    sa.Column('language_coverage', sa.String(length=32), nullable=False),
    sa.Column('analysis_error', sa.Text(), nullable=True),
    sa.Column('explanation_error', sa.Text(), nullable=True),
    sa.Column('comment_error', sa.Text(), nullable=True),
    sa.Column('context_notes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id')
    )
    op.create_table('revision_deltas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('revision_id', sa.Uuid(), nullable=False),
    sa.Column('previous_revision_id', sa.Uuid(), nullable=True),
    sa.Column('previous_head_sha', sa.String(length=64), nullable=True),
    sa.Column('added', sa.JSON(), nullable=False),
    sa.Column('removed', sa.JSON(), nullable=False),
    sa.Column('unchanged_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['previous_revision_id'], ['revisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id')
    )
    op.create_table('analysis_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('depth', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_run_id'), 'analysis_jobs', ['run_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_status'), 'analysis_jobs', ['status'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('epistemic', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('subject', sa.String(length=1024), nullable=True),
    sa.Column('evidence_public_ids', sa.JSON(), nullable=False),
    sa.Column('support_public_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_run_id'), 'claims', ['run_id'], unique=False)
    op.create_table('evidences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('repo', sa.String(length=512), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('file', sa.String(length=1024), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidences_run_id'), 'evidences', ['run_id'], unique=False)
    op.create_table('explanation_packets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('depth', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('selection_notes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'depth', name='uq_packet_run_depth')
    )
    op.create_table('explanations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('depth', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('document', sa.JSON(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'depth', name='uq_explanation_run_depth')
    )
    op.create_table('relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('source_public_id', sa.String(length=255), nullable=True),
    sa.Column('target_public_id', sa.String(length=255), nullable=True),
    sa.Column('source_name', sa.String(length=512), nullable=False),
    sa.Column('target_name', sa.String(length=512), nullable=False),
    sa.Column('source_file', sa.String(length=1024), nullable=True),
    sa.Column('target_file', sa.String(length=1024), nullable=True),
    sa.Column('evidence_public_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationships_run_id'), 'relationships', ['run_id'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('exported', sa.Boolean(), nullable=False),
    sa.Column('changed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_run_id'), 'symbols', ['run_id'], unique=False)
    op.create_table('claim_evidence',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('claim_id', 'evidence_id')
    )
    op.create_table('claim_support',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('support_claim_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['support_claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('claim_id', 'support_claim_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_support')
    op.drop_table('claim_evidence')
    op.drop_index(op.f('ix_symbols_run_id'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index(op.f('ix_relationships_run_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_table('explanations')
    op.drop_table('explanation_packets')
    op.drop_index(op.f('ix_evidences_run_id'), table_name='evidences')
    op.drop_table('evidences')
    op.drop_index(op.f('ix_claims_run_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_analysis_jobs_status'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_run_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_table('revision_deltas')
    op.drop_table('analysis_runs')
    op.drop_table('revisions')
    op.drop_table('pull_requests')
    op.drop_index(op.f('ix_repositories_installation_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_full_name'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_table('webhook_deliveries')
    op.drop_table('github_installations')
    # ### end Alembic commands ###
